version: "3.8"

networks:
  proxy:
    external: true

volumes:
  db_data:

services:
  db:
    image: mariadb:10.11
    container_name: dform-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: D05c0mm2022
      MYSQL_DATABASE: d_form_api
      MYSQL_USER: dform
      MYSQL_PASSWORD: dform_doscom
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy

  nginx:
    image: nginx:stable
    container_name: dform-nginx
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - backend
    networks:
      - proxy
    expose:
      - "80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dform-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    expose:
      - "9000"
